version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: fileshare_scanner
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: fileshare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 