services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: fileshare_scanner
      POSTGRES_PASSWORD: f00dballz
      POSTGRES_DB: fileshare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-17-data:/var/lib/postgresql/data  

volumes:
  postgres-17-data:
